-- Dirty Reads
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION
SELECT * FROM dbo.Ucznie
COMMIT
GO

-- Non-repeatable reads
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION
SELECT * FROM dbo.Ucznie

SELECT * FROM dbo.Ucznie
COMMIT
GO

-- Phantom reads
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION
SELECT * FROM dbo.Ucznie
WHERE [First Name] IN ('Piotr', 'Kuba')

SELECT * FROM dbo.Ucznie
WHERE [First Name] IN ('Piotr', 'Kuba')
COMMIT
GO


